apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
#      nodePort: 31476
      nodePort: 31500
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer